#default 공통설정
debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.ncookie.imad: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

--- # local 설정
spring:
  config:
    activate:
      on-profile: "db-local"
  datasource:
    url: jdbc:mysql://localhost:3306/imad
    username: uno
    password: thisisTESTpw!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  
--- # heroku 설정
spring:
  config:
    activate:
      on-profile: "db-heroku"
  datasource.url: ${JAWSDB_URL}
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always
